# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/shehyaaz/PycharmProjects/JiveMusicPlayer/venv/src/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(691, 529)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../resources/images/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.songThumbnail = QtWidgets.QLabel(self.centralWidget)
        self.songThumbnail.setMaximumSize(QtCore.QSize(1000, 800))
        self.songThumbnail.setStyleSheet("")
        self.songThumbnail.setText("")
        self.songThumbnail.setPixmap(QtGui.QPixmap("../../resources/images/Welcome.png"))
        self.songThumbnail.setScaledContents(False)
        self.songThumbnail.setAlignment(QtCore.Qt.AlignCenter)
        self.songThumbnail.setObjectName("songThumbnail")
        self.horizontalLayout.addWidget(self.songThumbnail)
        self.playlistView = QtWidgets.QListView(self.centralWidget)
        self.playlistView.setMinimumSize(QtCore.QSize(230, 0))
        self.playlistView.setMaximumSize(QtCore.QSize(230, 16777215))
        self.playlistView.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.playlistView.setObjectName("playlistView")
        self.horizontalLayout.addWidget(self.playlistView)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.currentTimeLabel = QtWidgets.QLabel(self.centralWidget)
        self.currentTimeLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.currentTimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentTimeLabel.setObjectName("currentTimeLabel")
        self.horizontalLayout_4.addWidget(self.currentTimeLabel)
        self.timeSlider = QtWidgets.QSlider(self.centralWidget)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.horizontalLayout_4.addWidget(self.timeSlider)
        self.totalTimeLabel = QtWidgets.QLabel(self.centralWidget)
        self.totalTimeLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.totalTimeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.totalTimeLabel.setObjectName("totalTimeLabel")
        self.horizontalLayout_4.addWidget(self.totalTimeLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.previousButton = QtWidgets.QPushButton(self.centralWidget)
        self.previousButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../resources/images/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon1)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout_5.addWidget(self.previousButton)
        self.playButton = QtWidgets.QPushButton(self.centralWidget)
        self.playButton.setEnabled(True)
        self.playButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../resources/images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon2)
        self.playButton.setCheckable(False)
        self.playButton.setAutoDefault(False)
        self.playButton.setDefault(False)
        self.playButton.setFlat(False)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_5.addWidget(self.playButton)
        self.stopButton = QtWidgets.QPushButton(self.centralWidget)
        self.stopButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../resources/images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon3)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_5.addWidget(self.stopButton)
        self.nextButton = QtWidgets.QPushButton(self.centralWidget)
        self.nextButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../resources/images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon4)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_5.addWidget(self.nextButton)
        self.infoButton = QtWidgets.QPushButton(self.centralWidget)
        self.infoButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../resources/images/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoButton.setIcon(icon5)
        self.infoButton.setObjectName("infoButton")
        self.horizontalLayout_5.addWidget(self.infoButton)
        self.lyricsButton = QtWidgets.QPushButton(self.centralWidget)
        self.lyricsButton.setObjectName("lyricsButton")
        self.horizontalLayout_5.addWidget(self.lyricsButton)
        self.volume = QtWidgets.QLabel(self.centralWidget)
        self.volume.setText("")
        self.volume.setTextFormat(QtCore.Qt.PlainText)
        self.volume.setPixmap(QtGui.QPixmap("../../resources/images/volume-down.png"))
        self.volume.setAlignment(QtCore.Qt.AlignCenter)
        self.volume.setObjectName("volume")
        self.horizontalLayout_5.addWidget(self.volume)
        self.volumeSlider = QtWidgets.QSlider(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volumeSlider.sizePolicy().hasHeightForWidth())
        self.volumeSlider.setSizePolicy(sizePolicy)
        self.volumeSlider.setAutoFillBackground(False)
        self.volumeSlider.setStyleSheet("")
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 40)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_5.addWidget(self.volumeSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 691, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFIle = QtWidgets.QMenu(self.menuBar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuPlaylists = QtWidgets.QMenu(self.menuBar)
        self.menuPlaylists.setObjectName("menuPlaylists")
        self.menuFavourites = QtWidgets.QMenu(self.menuBar)
        self.menuFavourites.setObjectName("menuFavourites")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuPreferences = QtWidgets.QMenu(self.menuBar)
        self.menuPreferences.setObjectName("menuPreferences")
        self.menuTheme = QtWidgets.QMenu(self.menuPreferences)
        self.menuTheme.setObjectName("menuTheme")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuPlay = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../resources/images/play_tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuPlay.setIcon(icon6)
        self.menuPlay.setObjectName("menuPlay")
        self.create_playlist = QtWidgets.QAction(MainWindow)
        self.create_playlist.setObjectName("create_playlist")
        self.view_playlist = QtWidgets.QAction(MainWindow)
        self.view_playlist.setObjectName("view_playlist")
        self.add_to_fav = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../resources/images/add_fav.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_to_fav.setIcon(icon7)
        self.add_to_fav.setObjectName("add_to_fav")
        self.add_to_playlist = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../resources/images/playlist_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_to_playlist.setIcon(icon8)
        self.add_to_playlist.setObjectName("add_to_playlist")
        self.exit_player = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../resources/images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_player.setIcon(icon9)
        self.exit_player.setObjectName("exit_player")
        self.new_playlist = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../resources/images/new_playlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_playlist.setIcon(icon10)
        self.new_playlist.setObjectName("new_playlist")
        self.play_playlist = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../resources/images/playlist_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_playlist.setIcon(icon11)
        self.play_playlist.setObjectName("play_playlist")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setIcon(icon5)
        self.about.setObjectName("about")
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionDefault = QtWidgets.QAction(MainWindow)
        self.actionDefault.setObjectName("actionDefault")
        self.actionFusion = QtWidgets.QAction(MainWindow)
        self.actionFusion.setObjectName("actionFusion")
        self.delete_playlist = QtWidgets.QAction(MainWindow)
        self.delete_playlist.setIcon(icon9)
        self.delete_playlist.setObjectName("delete_playlist")
        self.view_fav = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../resources/images/fav.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.view_fav.setIcon(icon12)
        self.view_fav.setObjectName("view_fav")
        self.search_playlist = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../resources/images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_playlist.setIcon(icon13)
        self.search_playlist.setObjectName("search_playlist")
        self.actionRemove_from_Playlist = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../../resources/images/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_from_Playlist.setIcon(icon14)
        self.actionRemove_from_Playlist.setObjectName("actionRemove_from_Playlist")
        self.actionRemove_from_Favourites = QtWidgets.QAction(MainWindow)
        self.actionRemove_from_Favourites.setIcon(icon14)
        self.actionRemove_from_Favourites.setObjectName("actionRemove_from_Favourites")
        self.menuFIle.addAction(self.menuPlay)
        self.menuFIle.addAction(self.add_to_fav)
        self.menuFIle.addAction(self.add_to_playlist)
        self.menuFIle.addAction(self.actionRemove_from_Playlist)
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.exit_player)
        self.menuPlaylists.addAction(self.new_playlist)
        self.menuPlaylists.addAction(self.play_playlist)
        self.menuPlaylists.addAction(self.delete_playlist)
        self.menuPlaylists.addAction(self.search_playlist)
        self.menuFavourites.addAction(self.view_fav)
        self.menuFavourites.addAction(self.actionRemove_from_Favourites)
        self.menuHelp.addAction(self.about)
        self.menuTheme.addAction(self.actionDefault)
        self.menuTheme.addAction(self.actionFusion)
        self.menuPreferences.addAction(self.menuTheme.menuAction())
        self.menuBar.addAction(self.menuFIle.menuAction())
        self.menuBar.addAction(self.menuPlaylists.menuAction())
        self.menuBar.addAction(self.menuFavourites.menuAction())
        self.menuBar.addAction(self.menuPreferences.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.menuPlay)
        self.toolBar.addAction(self.add_to_fav)
        self.toolBar.addAction(self.add_to_playlist)
        self.toolBar.addAction(self.new_playlist)
        self.toolBar.addAction(self.play_playlist)
        self.toolBar.addAction(self.view_fav)
        self.toolBar.addAction(self.search_playlist)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Jive Music Player"))
        self.currentTimeLabel.setText(_translate("MainWindow", "0:00"))
        self.totalTimeLabel.setText(_translate("MainWindow", "0:00"))
        self.infoButton.setToolTip(_translate("MainWindow", "Song Info"))
        self.lyricsButton.setText(_translate("MainWindow", "Lyrics"))
        self.menuFIle.setTitle(_translate("MainWindow", "File"))
        self.menuPlaylists.setTitle(_translate("MainWindow", "Playlist"))
        self.menuFavourites.setTitle(_translate("MainWindow", "Favourites"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuPreferences.setTitle(_translate("MainWindow", "Preferences"))
        self.menuTheme.setTitle(_translate("MainWindow", "Theme"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuPlay.setText(_translate("MainWindow", "Play"))
        self.create_playlist.setText(_translate("MainWindow", "Create Playlist"))
        self.view_playlist.setText(_translate("MainWindow", "View PLaylists"))
        self.add_to_fav.setText(_translate("MainWindow", "Add to Favourites"))
        self.add_to_playlist.setText(_translate("MainWindow", "Add to Playlist"))
        self.exit_player.setText(_translate("MainWindow", "Exit"))
        self.exit_player.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.new_playlist.setText(_translate("MainWindow", "New Playlist"))
        self.play_playlist.setText(_translate("MainWindow", "Play Playlist"))
        self.about.setText(_translate("MainWindow", "About"))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file.."))
        self.actionDefault.setText(_translate("MainWindow", "Default"))
        self.actionFusion.setText(_translate("MainWindow", "Fusion"))
        self.delete_playlist.setText(_translate("MainWindow", "Delete Playlist"))
        self.view_fav.setText(_translate("MainWindow", "Play Favourites"))
        self.search_playlist.setText(_translate("MainWindow", "Search Playlist"))
        self.actionRemove_from_Playlist.setText(_translate("MainWindow", "Remove from Playlist"))
        self.actionRemove_from_Favourites.setText(_translate("MainWindow", "Remove from Favourites"))
