# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 371)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.playlistView = QtWidgets.QListView(self.centralWidget)
        self.playlistView.setAcceptDrops(True)
        self.playlistView.setProperty("showDropIndicator", True)
        self.playlistView.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.playlistView.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.playlistView.setAlternatingRowColors(True)
        self.playlistView.setUniformItemSizes(True)
        self.playlistView.setObjectName("playlistView")
        self.verticalLayout.addWidget(self.playlistView)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.currentTimeLabel = QtWidgets.QLabel(self.centralWidget)
        self.currentTimeLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.currentTimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentTimeLabel.setObjectName("currentTimeLabel")
        self.horizontalLayout_4.addWidget(self.currentTimeLabel)
        self.timeSlider = QtWidgets.QSlider(self.centralWidget)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.horizontalLayout_4.addWidget(self.timeSlider)
        self.totalTimeLabel = QtWidgets.QLabel(self.centralWidget)
        self.totalTimeLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.totalTimeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.totalTimeLabel.setObjectName("totalTimeLabel")
        self.horizontalLayout_4.addWidget(self.totalTimeLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.previousButton = QtWidgets.QPushButton(self.centralWidget)
        self.previousButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout_5.addWidget(self.previousButton)
        self.playButton = QtWidgets.QPushButton(self.centralWidget)
        self.playButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon1)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_5.addWidget(self.playButton)
        self.stopButton = QtWidgets.QPushButton(self.centralWidget)
        self.stopButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_5.addWidget(self.stopButton)
        self.nextButton = QtWidgets.QPushButton(self.centralWidget)
        self.nextButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon3)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_5.addWidget(self.nextButton)
        self.loopButton = QtWidgets.QPushButton(self.centralWidget)
        self.loopButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/loop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loopButton.setIcon(icon4)
        self.loopButton.setObjectName("loopButton")
        self.horizontalLayout_5.addWidget(self.loopButton)
        self.volume = QtWidgets.QLabel(self.centralWidget)
        self.volume.setText("")
        self.volume.setPixmap(QtGui.QPixmap("images/volume-down.png"))
        self.volume.setObjectName("volume")
        self.horizontalLayout_5.addWidget(self.volume)
        self.volumeSlider = QtWidgets.QSlider(self.centralWidget)
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 100)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_5.addWidget(self.volumeSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 484, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFIle = QtWidgets.QMenu(self.menuBar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuPlaylists = QtWidgets.QMenu(self.menuBar)
        self.menuPlaylists.setObjectName("menuPlaylists")
        self.menuFavourites = QtWidgets.QMenu(self.menuBar)
        self.menuFavourites.setObjectName("menuFavourites")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.add_to_queue = QtWidgets.QAction(MainWindow)
        self.add_to_queue.setObjectName("add_to_queue")
        self.create_playlist = QtWidgets.QAction(MainWindow)
        self.create_playlist.setObjectName("create_playlist")
        self.view_playlist = QtWidgets.QAction(MainWindow)
        self.view_playlist.setObjectName("view_playlist")
        self.add_to_fav = QtWidgets.QAction(MainWindow)
        self.add_to_fav.setObjectName("add_to_fav")
        self.add_to_playlist = QtWidgets.QAction(MainWindow)
        self.add_to_playlist.setObjectName("add_to_playlist")
        self.exit_player = QtWidgets.QAction(MainWindow)
        self.exit_player.setObjectName("exit_player")
        self.new_playlist = QtWidgets.QAction(MainWindow)
        self.new_playlist.setObjectName("new_playlist")
        self.view_playlists = QtWidgets.QAction(MainWindow)
        self.view_playlists.setObjectName("view_playlists")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.menuFIle.addAction(self.actionOpen_file)
        self.menuFIle.addAction(self.add_to_queue)
        self.menuFIle.addAction(self.add_to_fav)
        self.menuFIle.addAction(self.add_to_playlist)
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.exit_player)
        self.menuPlaylists.addAction(self.new_playlist)
        self.menuPlaylists.addAction(self.view_playlists)
        self.menuHelp.addAction(self.about)
        self.menuBar.addAction(self.menuFIle.menuAction())
        self.menuBar.addAction(self.menuPlaylists.menuAction())
        self.menuBar.addAction(self.menuFavourites.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Failamp"))
        self.currentTimeLabel.setText(_translate("MainWindow", "0:00"))
        self.totalTimeLabel.setText(_translate("MainWindow", "0:00"))
        self.menuFIle.setTitle(_translate("MainWindow", "File"))
        self.menuPlaylists.setTitle(_translate("MainWindow", "Playlist"))
        self.menuFavourites.setTitle(_translate("MainWindow", "Favourites"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.add_to_queue.setText(_translate("MainWindow", "Add to Queue"))
        self.create_playlist.setText(_translate("MainWindow", "Create Playlist"))
        self.view_playlist.setText(_translate("MainWindow", "View PLaylists"))
        self.add_to_fav.setText(_translate("MainWindow", "Add to Favourites"))
        self.add_to_playlist.setText(_translate("MainWindow", "Add to Playlist"))
        self.exit_player.setText(_translate("MainWindow", "Exit"))
        self.new_playlist.setText(_translate("MainWindow", "New Playlist"))
        self.view_playlists.setText(_translate("MainWindow", "View Playlist"))
        self.about.setText(_translate("MainWindow", "About"))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file.."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
